#' ichorViz: explore and compare ichorCNA profiles
#'
#' ichorViz consumes output generated by ichorCNA. It provides validated data
#' objects, genome-wide and regional plots, paired or multi-sample comparisons,
#' and cohort-scale matrices and heatmaps.
#'
#' @keywords internal
"_PACKAGE"

utils::globalVariables(c(
  "chr", "start", "end", "mid", "x", "xend", "logR", "median",
  "state", "sample", "value", "bin_index", "overlap", "weighted"
))
